# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    base_url: 'https://www.short.link/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Service/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\HashingService\HashingService: ~

    App\Controller\LinkShortenerController:
        arguments:
            $hashingService: '@App\Service\HashingService\HashingService'
        tags:
            - { name: 'controller.service_arguments' }

    App\Controller\QrCodeGeneratorController:
        arguments:
            $folder_path: '%kernel.project_dir%/public/img/QrCodes/'
        tags:
            - { name: 'controller.service_arguments' }

    App\Controller\LinkRedirectController:
        arguments:
            $shortLinkRepository: '@App\Repository\ShortLinkRepository\ShortLinkRepositoryImpl'
            $existenceChecker: '@App\Service\LinkService\LinkExistenceChecker\LinkExistenceChecker'
        tags:
            - { name: 'controller.service_arguments' }

    App\Service\LinkService\LinkExistenceChecker\LinkExistenceChecker:
        autowire: true

    App\Service\LinkService\LinkExpirationChecker\LinkExpirationChecker:
        autowire: true
        arguments:
            $shortLinkRepository: '@App\Repository\ShortLinkRepository\ShortLinkRepositoryImpl'
            $expirationThreshold: 3600

    App\Service\Validator\UrlValidator: ~

    App\Service\QrService\QrConfigurator\QrConfigurator:
        autowire: true
        arguments:
            $folder_path: '%kernel.project_dir%/public/img/QrCodes/'


